noun = input("Insert noun: ")
verb = input("Insert verb: ")
adjective = input("Insert adjective: ")
place = input("Insert place: ")
time = int(input("Insert time in minutes: "))
print(f"The {noun} {verb} {adjective} to {place} in {time} minutes")